os: linux
dist: bionic
language: rust
rust: nightly
#cache: cargo
services:
  - docker

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - holy
    - master

jobs:
  include:
    # Linux
    - env: name="linux-arm-32" arch="armv7-unknown-linux-gnueabihf"
    - env: name="linux-arm-64" arch="aarch64-unknown-linux-gnu"
    - env: name="linux-intel-32" arch="i686-unknown-linux-gnu"
    - env: name="linux-intel-64" arch="x86_64-unknown-linux-gnu"

    # MacOS
    - os: osx
      env: name="macos-intel-32" arch="i686-apple-darwin" 
    - os: osx
      env: name="macos-intel-64" arch="x86_64-apple-darwin"

    # BSD
    #- env: name="bsd-intel-32" arch="i686-unknown-freebsd"
    #- env: name="bsd-intel-64" arch="x86_64-unknown-freebsd"

install:
  - cargo install cross

before_script:
  - ci/prepare-toolchain.sh "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" "${arch}"

script:
  - cross build --target "${arch}" ${TRAVIS_TAG:+"--release"}

before_deploy:
  - release="hunter-${TRAVIS_BRANCH}-${name}"
  - mkdir "${release}"
  - cp "target/${arch}/release/hunter" "${release}/"
  - cp README.md LICENSE "${release}/"
  - cp --recursive extra "${release}/"
  - GZIP=-9 tar --create --gzip --verbose --file="${release}.tar.gz" "${release}"/*

deploy:
  provider: releases
  edge: yes
  token: $GITHUB_OAUTH
  file: hunter-$TRAVIS_BRANCH-$arch.tar.gz
  draft: yes
  on:
    tags: yes

notifications:
  email:
    no
