[target.armv7-unknown-linux-gnueabihf]
image = "stopbugging/cross-armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "stopbugging/cross-aarch64-unknown-linux-gnu"

[target.i686-unknown-linux-gnu]
image = "stopbugging/cross-i686-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "stopbugging/cross-x86_64-unknown-linux-gnu"
